image:
  repository: ghcr.io/in-toto/archivista
  tag: "0.4.0"

ingress:
  enabled: false

deployment:
  envFrom:
    # Database Configuration
    - secretRef:
        name: archivista-postgres
    # Object Store Configuration
    - secretRef:
        name: archivista-object-store
