# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

ingress:
  enabled: false

serviceAccount:
  create: true
  annotations: {}

deployment:
  env:
    - name: ARCHIVISTA_LISTEN_ON
      value: tcp://0.0.0.0:8082

  envFrom:
    # Database Configuration
    - secretRef:
        name: archivista-postgres
    # Object Store Configuration
    - secretRef:
        name: archivista-object-store
