# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: archivista-object-store
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ARCHIVISTA_STORAGE_BACKEND: "BLOB"
  ARCHIVISTA_BLOB_STORE_ENDPOINT: {{ .Values.storage.endpoint | quote }}
  ARCHIVISTA_BLOB_STORE_USE_TLS: {{ .Values.storage.secure | toString | quote }}
  ARCHIVISTA_BLOB_STORE_BUCKET_NAME: {{ .Values.storage.bucket | quote }}
  {{- if or (.Values.storage.accessKey) (.Values.storage.secretKey) }}
  ARCHIVISTA_BLOB_STORE_CREDENTIAL_TYPE: "ACCESS_KEY"
  ARCHIVISTA_BLOB_STORE_ACCESS_KEY_ID: {{ .Values.storage.accessKey | quote }}
  ARCHIVISTA_BLOB_STORE_SECRET_ACCESS_KEY_ID: {{ .Values.storage.secretKey | quote }}
  {{- else }}
  ARCHIVISTA_BLOB_STORE_CREDENTIAL_TYPE: "IAM"
  {{- end }}
