tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress
      - task: api

  - name: health-check
    actions:
      - description: Archivista Health Check
        wait:
          cluster:
            kind: Deployment
            name: archivista
            namespace: archivista
            condition: Available

  - name: ingress
    actions:
      - description: Archivista UI Health Check
        wait:
          network:
            protocol: https
            address: archivista.uds.dev
            code: 200

  - name: api
    actions:
      - description: Archivista API Tests
      - cmd: bash test.bash
        dir: tests
